services:
  news-mcp:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # 构建时代理设置 (仅在需要时使用)
        - HTTP_PROXY=${BUILD_HTTP_PROXY:-}
        - HTTPS_PROXY=${BUILD_HTTPS_PROXY:-}
        - NO_PROXY=${NO_PROXY:-localhost,127.0.0.1}
      network: host
    container_name: news-mcp-server
    ports:
      - "${PORT:-8000}:8000"
    environment:
      # 运行时代理设置
      - HTTP_PROXY=${HTTP_PROXY:-}
      - HTTPS_PROXY=${HTTPS_PROXY:-}
      - NO_PROXY=${NO_PROXY:-localhost,127.0.0.1}
      # 应用配置
      - NEWS_MCP_CUSTOM_FEEDS=${NEWS_MCP_CUSTOM_FEEDS:-}
      - PYTHONUNBUFFERED=${PYTHONUNBUFFERED:-1}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      # 挂载配置文件
      - ./config:/app/config:ro
      # 挂载日志目录
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - news-mcp-network

  # Nginx 反向代理 (可选)
  nginx:
    image: nginx:alpine
    container_name: news-mcp-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - news-mcp
    restart: unless-stopped
    networks:
      - news-mcp-network
    profiles:
      - with-nginx

networks:
  news-mcp-network:
    driver: bridge
